FROM docker.io/library/alpine:3.19

RUN apk add --no-cache \
    mpd \
    mpc \
    alsa-lib \
    alsa-plugins-pulse \
    pulseaudio-utils \
    && mkdir -p /var/lib/mpd/music \
                /var/lib/mpd/playlists \
                /var/lib/mpd/data \
    && chown -R mpd:audio /var/lib/mpd

COPY mpd.conf /etc/mpd.conf

EXPOSE 6600

# Run as current user via --userns=keep-id when starting container
ENTRYPOINT ["mpd", "--no-daemon", "/etc/mpd.conf"]
