context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "RME Out 1/2 (Line Out + PH 1/2)"
            capture.props = {
                node.name = "rme-out-1-2"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                target.object = "alsa_output.usb-RME_ADI-2_4_Pro_SE__53011083__B992903C2BD8DC8-00.pro-output-0"
                audio.position = [ AUX0 AUX1 ]
                node.passive = false
                node.dont-reconnect = true
                stream.dont-remix = true
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "RME Out 3/4 (PH 3/4 / Pentaconn)"
            capture.props = {
                node.name = "rme-out-3-4"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                target.object = "alsa_output.usb-RME_ADI-2_4_Pro_SE__53011083__B992903C2BD8DC8-00.pro-output-0"
                audio.position = [ AUX2 AUX3 ]
                node.passive = false
                node.dont-reconnect = true
                stream.dont-remix = true
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "RME Out 5/6 (AES)"
            capture.props = {
                node.name = "rme-out-5-6"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                target.object = "alsa_output.usb-RME_ADI-2_4_Pro_SE__53011083__B992903C2BD8DC8-00.pro-output-0"
                audio.position = [ AUX4 AUX5 ]
                node.passive = false
                node.dont-reconnect = true
                stream.dont-remix = true
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "RME Out 7/8 (SPDIF)"
            capture.props = {
                node.name = "rme-out-7-8"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                target.object = "alsa_output.usb-RME_ADI-2_4_Pro_SE__53011083__B992903C2BD8DC8-00.pro-output-0"
                audio.position = [ AUX6 AUX7 ]
                node.passive = false
                node.dont-reconnect = true
                stream.dont-remix = true
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            node.description = "RME Mic"
            capture.props = {
                target.object = "alsa_input.usb-RME_ADI-2_4_Pro_SE__53011083__B992903C2BD8DC8-00.pro-input-0"
                audio.position = [ AUX0 AUX1 ]
                node.dont-reconnect = true
                stream.dont-remix = true
            }
            playback.props = {
                node.name = "rme-mic"
                media.class = "Audio/Source"
                audio.position = [ FL FR ]
            }
        }
    }
]
