#!/usr/bin/env python3
"""Generate Salt state, macro, and data indexes for Claude Code memory.

Parses macro .jinja files for signatures, renders .sls with mock Jinja env
for state IDs and require chains, and summarizes YAML data files.

Reuses parsing infrastructure from lint-jinja.py.

Outputs markdown to memory/generated/salt-macros.md, salt-states.md, salt-data.md.
"""

import glob
import importlib.util
import json
import os
import re
import sys
from datetime import datetime

import yaml

# Host model from shared module; lint-jinja.py for Jinja rendering infrastructure
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

# lint-jinja.py has a hyphenated name — must use importlib.util
_lint_path = os.path.join(SCRIPTS_DIR, "lint-jinja.py")
_spec = importlib.util.spec_from_file_location("lint_jinja", _lint_path)
if not _spec or not _spec.loader:  # pragma: no cover - defensive
    raise ImportError("Cannot load lint-jinja.py")
_lint_jinja = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_lint_jinja)  # type: ignore[attr-defined]

SaltTagExtension = _lint_jinja.SaltTagExtension
_make_render_env = _lint_jinja._make_render_env
_resolve_import_yaml = _lint_jinja._resolve_import_yaml

STATES_DIR = "states"
MEMORY_DIR = os.path.join(
    os.path.expanduser("~"), ".claude", "projects", "-home-neg-src-salt", "memory", "generated"
)
DOCS_DIR = "docs"

_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
HEADER = (
    "<!-- AUTO-GENERATED by scripts/index-salt.py"
    " — do not hand-edit -->\n"
    f"<!-- Last updated: {_ts} -->\n"
)

SALT_DIRECTIVES = frozenset({"include", "extend"})
REQUISITE_KEYS = frozenset(
    {
        "require",
        "watch",
        "onchanges",
        "onfail",
        "prereq",
        "require_in",
        "watch_in",
        "onchanges_in",
        "onfail_in",
    }
)

IMPORT_YAML_RE = re.compile(r"\{%-?\s*import_yaml\s+['\"]([^'\"]+)['\"]\s+as\s+\w+")

# --- Macro parsing ---

MACRO_DEF_RE = re.compile(r"\{%-?\s*macro\s+(\w+)\s*\((.*?)\)\s*-?%\}", re.DOTALL)


def parse_macros(jinja_files):
    """Parse macro definitions from .jinja files.

    Returns list of (name, params_str, source_file, doc_comment).
    """
    macros = []
    for path in sorted(jinja_files):
        with open(path) as f:
            source = f.read()

        rel = os.path.relpath(path)
        # Find doc comments immediately before macros
        for m in MACRO_DEF_RE.finditer(source):
            name = m.group(1)
            params = m.group(2).strip()
            # Look for {# ... #} comment in the 500 chars before macro
            pre = source[max(0, m.start() - 500) : m.start()]
            doc = ""
            doc_m = re.search(r"\{#\s*(.*?)\s*#\}", pre, re.DOTALL)
            if doc_m:
                doc = doc_m.group(1).strip().split("\n")[0].strip()
            macros.append((name, params, rel, doc))
    return macros


def generate_macros_md(macros):
    """Generate salt-macros.md content."""
    lines = [HEADER, "# Salt Macro Index\n"]

    by_file = {}
    for name, params, src, doc in macros:
        by_file.setdefault(src, []).append((name, params, doc))

    for src in sorted(by_file):
        lines.append(f"\n## `{src}`\n")
        for name, params, doc in by_file[src]:
            lines.append(f"### {name}")
            lines.append(f"```\n{name}({params})\n```")
            if doc:
                lines.append(f"_{doc}_")
            lines.append("")

    return "\n".join(lines) + "\n"


# --- State rendering and dependency extraction ---


def render_states(sls_files):
    """Render .sls files with mock context, extract state IDs and requisites.

    Returns list of (rel_path, state_ids, includes, requires, feature_guards).
    """
    env = _make_render_env()
    results = []

    for path in sorted(sls_files):
        rel = os.path.relpath(path)
        name = path.removeprefix(f"{STATES_DIR}/")
        try:
            t = env.get_template(name)
            with open(path) as fh:
                yaml_vars = _resolve_import_yaml(fh.read())
            rendered = t.render(**yaml_vars)
        except Exception:
            results.append((rel, [], [], [], []))
            continue

        state_ids = []
        includes = []
        requires = []

        try:
            for doc in yaml.safe_load_all(rendered):
                if not doc or not isinstance(doc, dict):
                    continue
                for key, val in doc.items():
                    if key == "include":
                        if isinstance(val, list):
                            includes.extend(str(v) for v in val)
                    elif key not in SALT_DIRECTIVES:
                        state_ids.append(key)
                        # Extract require chains
                        if isinstance(val, dict):
                            for state_mod, state_args in val.items():
                                if isinstance(state_args, list):
                                    for arg in state_args:
                                        if isinstance(arg, dict):
                                            for rk in REQUISITE_KEYS:
                                                if rk in arg:
                                                    reqs = arg[rk]
                                                    if isinstance(reqs, list):
                                                        for r in reqs:
                                                            if isinstance(r, dict):
                                                                for mod, sid in r.items():
                                                                    req = f"{mod}: {sid}"
                                                                    requires.append((key, req))
        except Exception:
            pass

        # Scan raw source for feature guards
        feature_guards = []
        with open(path) as fh:
            raw = fh.read()
        for fm in re.finditer(r"host\.features\.(\w+(?:\.\w+)*)", raw):
            feat = fm.group(1)
            if feat not in feature_guards:
                feature_guards.append(feat)

        results.append((rel, state_ids, includes, requires, feature_guards))

    return results


def generate_states_md(state_results):
    """Generate salt-states.md content."""
    lines = [HEADER, "# Salt State Index\n"]

    for rel, state_ids, includes, requires, guards in state_results:
        basename = os.path.basename(rel).replace(".sls", "")
        lines.append(f"\n## {basename}")
        lines.append(f"**File:** `{rel}`\n")

        if includes:
            lines.append(f"**Includes:** {', '.join(f'`{i}`' for i in includes)}\n")

        if guards:
            lines.append(f"**Feature guards:** {', '.join(f'`{g}`' for g in guards)}\n")

        if state_ids:
            lines.append(f"**State IDs** ({len(state_ids)}):")
            for sid in state_ids:
                lines.append(f"- `{sid}`")
            lines.append("")

        if requires:
            lines.append("**Require chains:**")
            for from_id, to_ref in requires:
                lines.append(f"- `{from_id}` requires `{to_ref}`")
            lines.append("")

    return "\n".join(lines) + "\n"


def build_state_graph(state_results):
    graph = {}
    reverse = {}
    guards_map = {}
    for rel, _, includes, _, guards in state_results:
        name = os.path.basename(rel).replace(".sls", "")
        clean_includes = [inc.strip() for inc in includes if inc]
        graph[name] = clean_includes
        guards_map[name] = guards
        for inc in clean_includes:
            reverse.setdefault(inc, []).append(name)
        reverse.setdefault(name, reverse.get(name, []))
    return graph, reverse, guards_map


def generate_state_map_docs(graph, reverse, guards_map):
    eng = [
        HEADER,
        "# Salt State Dependency Map\n",
        "Generated from `include:` statements in `states/*.sls`.\n",
    ]
    rus = [
        HEADER,
        "# Карта зависимостей Salt\n",
        "Сгенерировано из блоков `include:` в `states/*.sls`.\n",
    ]

    def fmt_list(items, empty):
        return ", ".join(f"`{item}`" for item in sorted(set(items))) if items else empty

    for state in sorted(graph):
        includes = graph[state]
        parents = reverse.get(state, [])
        guards = guards_map.get(state, [])

        eng.append(f"\n## `{state}`")
        eng.append(f"**Includes:** {fmt_list(includes, '_None_')}\n")
        eng.append(f"**Included by:** {fmt_list(parents, '_Root_')}\n")
        if guards:
            eng.append(f"**Feature guards:** {fmt_list(guards, '_None_')}\n")

        rus.append(f"\n## `{state}`")
        rus.append(f"**Включает:** {fmt_list(includes, '_Нет_')}\n")
        rus.append(f"**Используется в:** {fmt_list(parents, '_Корень_')}\n")
        if guards:
            rus.append(f"**Фичи:** {fmt_list(guards, '_Нет_')}\n")

    return "\n".join(eng) + "\n", "\n".join(rus) + "\n"


def write_knowledge_base(macros, state_results, summaries):
    kb_path = os.path.join(MEMORY_DIR, "salt-knowledge.jsonl")
    with open(kb_path, "w") as fh:
        for name, params, src, doc in macros:
            json.dump(
                {
                    "type": "macro",
                    "name": name,
                    "file": src,
                    "params": params,
                    "doc": doc,
                },
                fh,
            )
            fh.write("\n")

        for rel, state_ids, includes, requires, guards in state_results:
            fh.write(
                json.dumps(
                    {
                        "type": "state",
                        "name": os.path.basename(rel).replace(".sls", ""),
                        "file": rel,
                        "state_ids": state_ids,
                        "includes": includes,
                        "requires": requires,
                        "feature_guards": guards,
                    }
                )
                + "\n"
            )

        for rel, info in summaries:
            fh.write(
                json.dumps(
                    {
                        "type": "data",
                        "file": rel,
                        "info": info,
                    }
                )
                + "\n"
            )
    print(f"Wrote {kb_path}")


# --- Data file summaries ---


def summarize_data_files():
    """Summarize YAML data files in states/data/."""
    data_dir = os.path.join(STATES_DIR, "data")
    if not os.path.isdir(data_dir):
        return []

    summaries = []
    for path in sorted(glob.glob(os.path.join(data_dir, "*.yaml"))):
        rel = os.path.relpath(path)
        try:
            with open(path) as f:
                data = yaml.safe_load(f.read())
        except Exception:
            summaries.append((rel, "Failed to parse"))
            continue

        if not isinstance(data, dict):
            summaries.append((rel, f"Root type: {type(data).__name__}"))
            continue

        sections = []
        for key, val in data.items():
            if isinstance(val, dict):
                sections.append(f"`{key}` ({len(val)} entries)")
            elif isinstance(val, list):
                sections.append(f"`{key}` ({len(val)} items)")
            else:
                sections.append(f"`{key}`: {val}")

        summaries.append((rel, sections))

    return summaries


def generate_data_md(summaries):
    """Generate salt-data.md content."""
    lines = [HEADER, "# Salt Data File Index\n"]

    for rel, info in summaries:
        basename = os.path.basename(rel)
        lines.append(f"\n## {basename}")
        lines.append(f"**File:** `{rel}`\n")

        if isinstance(info, str):
            lines.append(f"_{info}_\n")
        else:
            for section in info:
                lines.append(f"- {section}")
            lines.append("")

    return "\n".join(lines) + "\n"


def collect_data_usage():
    usage = {}
    for path in glob.glob(os.path.join(STATES_DIR, "*.sls")):
        with open(path) as f:
            content = f.read()
        for match in IMPORT_YAML_RE.finditer(content):
            rel = match.group(1)
            if not rel.startswith("data/"):
                continue
            full = os.path.join(STATES_DIR, rel)
            usage.setdefault(full, set()).add(os.path.basename(path))
    return {k: sorted(v) for k, v in usage.items()}


def _fmt_list(items, empty_text):
    return ", ".join(f"`{item}`" for item in sorted(set(items))) if items else empty_text


def generate_data_inventory_docs(summaries, usage):
    info_map = {rel: info for rel, info in summaries}
    eng = [
        HEADER,
        "# Data Inventory\n",
        "Mapping of `states/data/*.yaml` sections to consumer states.\n",
    ]
    rus = [
        HEADER,
        "# Инвентарь data-файлов\n",
        "Связь `states/data/*.yaml` и состояний, которые их импортируют.\n",
    ]

    for rel in sorted(info_map):
        consumers = usage.get(rel, [])
        sections = info_map[rel]

        eng.append(f"\n## `{rel}`")
        eng.append(f"**Used by:** {_fmt_list(consumers, '_Unused_')}\n")
        if isinstance(sections, str):
            eng.append(f"_{sections}_\n")
        else:
            for section in sections:
                eng.append(f"- {section}")
            eng.append("")

        rus.append(f"\n## `{rel}`")
        rus.append(f"**Используют:** {_fmt_list(consumers, '_Не используется_')}\n")
        if isinstance(sections, str):
            rus.append(f"_{sections}_\n")
        else:
            for section in sections:
                rus.append(f"- {section}")
            rus.append("")

    return "\n".join(eng) + "\n", "\n".join(rus) + "\n"


def main():
    if not os.path.isdir(STATES_DIR):
        print(f"Error: {STATES_DIR} not found. Run from project root.", file=sys.stderr)
        sys.exit(1)

    os.makedirs(MEMORY_DIR, exist_ok=True)
    os.makedirs(DOCS_DIR, exist_ok=True)

    # 1. Macros
    jinja_files = sorted(glob.glob(os.path.join(STATES_DIR, "_macros_*.jinja")))
    macros = parse_macros(jinja_files)
    macros_md = generate_macros_md(macros)
    macros_path = os.path.join(MEMORY_DIR, "salt-macros.md")
    with open(macros_path, "w") as f:
        f.write(macros_md)
    print(f"Wrote {macros_path} ({len(macros)} macros, {macros_md.count(chr(10))} lines)")

    # 2. States
    sls_files = sorted(glob.glob(os.path.join(STATES_DIR, "*.sls")))
    state_results = render_states(sls_files)
    rendered_ok = sum(1 for _, ids, _, _, _ in state_results if ids)
    states_md = generate_states_md(state_results)
    states_path = os.path.join(MEMORY_DIR, "salt-states.md")
    with open(states_path, "w") as f:
        f.write(states_md)
    n_lines = states_md.count(chr(10))
    print(f"Wrote {states_path} ({len(sls_files)} files, {rendered_ok} rendered, {n_lines} lines)")

    # 3. Data files
    summaries = summarize_data_files()
    data_md = generate_data_md(summaries)
    data_path = os.path.join(MEMORY_DIR, "salt-data.md")
    with open(data_path, "w") as f:
        f.write(data_md)
    print(f"Wrote {data_path} ({len(summaries)} files, {data_md.count(chr(10))} lines)")

    usage = collect_data_usage()
    eng_inventory, rus_inventory = generate_data_inventory_docs(summaries, usage)
    inventory_path = os.path.join(DOCS_DIR, "data-inventory.md")
    inventory_ru_path = os.path.join(DOCS_DIR, "data-inventory.ru.md")
    with open(inventory_path, "w") as f:
        f.write(eng_inventory)
    with open(inventory_ru_path, "w") as f:
        f.write(rus_inventory)
    print(f"Wrote {inventory_path} and {inventory_ru_path}")

    # 4. State dependency map docs
    graph, reverse, guards_map = build_state_graph(state_results)
    eng_map, rus_map = generate_state_map_docs(graph, reverse, guards_map)
    eng_path = os.path.join(DOCS_DIR, "state-map.md")
    rus_path = os.path.join(DOCS_DIR, "state-map.ru.md")
    with open(eng_path, "w") as f:
        f.write(eng_map)
    with open(rus_path, "w") as f:
        f.write(rus_map)
    print(f"Wrote {eng_path} and {rus_path}")

    write_knowledge_base(macros, state_results, summaries)


if __name__ == "__main__":
    main()
