#!/usr/bin/env python3
"""Generate Salt state, macro, and data indexes for Claude Code memory.

Parses macro .jinja files for signatures, renders .sls with mock Jinja env
for state IDs and require chains, and summarizes YAML data files.

Reuses parsing infrastructure from lint-jinja.py.

Outputs markdown to memory/generated/salt-macros.md, salt-states.md, salt-data.md.
"""

import glob
import importlib.util
import os
import re
import sys
from datetime import datetime

import yaml

# Reuse lint-jinja.py infrastructure (hyphenated filename requires importlib)
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
_lint_path = os.path.join(SCRIPTS_DIR, "lint-jinja.py")
_spec = importlib.util.spec_from_file_location("lint_jinja", _lint_path)
_lint_jinja = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_lint_jinja)

SaltTagExtension = _lint_jinja.SaltTagExtension
_make_render_env = _lint_jinja._make_render_env
_resolve_import_yaml = _lint_jinja._resolve_import_yaml
_extract_dict_literal = _lint_jinja._extract_dict_literal
_build_lint_host = _lint_jinja._build_lint_host
_enable_all_features = _lint_jinja._enable_all_features

STATES_DIR = "states"
MEMORY_DIR = os.path.join(
    os.path.expanduser("~"), ".claude", "projects", "-home-neg-src-salt", "memory", "generated"
)

_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
HEADER = (
    "<!-- AUTO-GENERATED by scripts/index-salt.py"
    " — do not hand-edit -->\n"
    f"<!-- Last updated: {_ts} -->\n"
)

SALT_DIRECTIVES = frozenset({"include", "extend"})
REQUISITE_KEYS = frozenset(
    {
        "require",
        "watch",
        "onchanges",
        "onfail",
        "prereq",
        "require_in",
        "watch_in",
        "onchanges_in",
        "onfail_in",
    }
)

# --- Macro parsing ---

MACRO_DEF_RE = re.compile(r"\{%-?\s*macro\s+(\w+)\s*\((.*?)\)\s*-?%\}", re.DOTALL)


def parse_macros(jinja_files):
    """Parse macro definitions from .jinja files.

    Returns list of (name, params_str, source_file, doc_comment).
    """
    macros = []
    for path in sorted(jinja_files):
        with open(path) as f:
            source = f.read()

        rel = os.path.relpath(path)
        # Find doc comments immediately before macros
        for m in MACRO_DEF_RE.finditer(source):
            name = m.group(1)
            params = m.group(2).strip()
            # Look for {# ... #} comment in the 500 chars before macro
            pre = source[max(0, m.start() - 500) : m.start()]
            doc = ""
            doc_m = re.search(r"\{#\s*(.*?)\s*#\}", pre, re.DOTALL)
            if doc_m:
                doc = doc_m.group(1).strip().split("\n")[0].strip()
            macros.append((name, params, rel, doc))
    return macros


def generate_macros_md(macros):
    """Generate salt-macros.md content."""
    lines = [HEADER, "# Salt Macro Index\n"]

    by_file = {}
    for name, params, src, doc in macros:
        by_file.setdefault(src, []).append((name, params, doc))

    for src in sorted(by_file):
        lines.append(f"\n## `{src}`\n")
        for name, params, doc in by_file[src]:
            lines.append(f"### {name}")
            lines.append(f"```\n{name}({params})\n```")
            if doc:
                lines.append(f"_{doc}_")
            lines.append("")

    return "\n".join(lines) + "\n"


# --- State rendering and dependency extraction ---


def render_states(sls_files):
    """Render .sls files with mock context, extract state IDs and requisites.

    Returns list of (rel_path, state_ids, includes, requires, feature_guards).
    """
    env = _make_render_env()
    results = []

    for path in sorted(sls_files):
        rel = os.path.relpath(path)
        name = path.removeprefix(f"{STATES_DIR}/")
        try:
            t = env.get_template(name)
            with open(path) as fh:
                yaml_vars = _resolve_import_yaml(fh.read())
            rendered = t.render(**yaml_vars)
        except Exception:
            results.append((rel, [], [], [], []))
            continue

        state_ids = []
        includes = []
        requires = []

        try:
            for doc in yaml.safe_load_all(rendered):
                if not doc or not isinstance(doc, dict):
                    continue
                for key, val in doc.items():
                    if key == "include":
                        if isinstance(val, list):
                            includes.extend(str(v) for v in val)
                    elif key not in SALT_DIRECTIVES:
                        state_ids.append(key)
                        # Extract require chains
                        if isinstance(val, dict):
                            for state_mod, state_args in val.items():
                                if isinstance(state_args, list):
                                    for arg in state_args:
                                        if isinstance(arg, dict):
                                            for rk in REQUISITE_KEYS:
                                                if rk in arg:
                                                    reqs = arg[rk]
                                                    if isinstance(reqs, list):
                                                        for r in reqs:
                                                            if isinstance(r, dict):
                                                                for mod, sid in r.items():
                                                                    req = f"{mod}: {sid}"
                                                                    requires.append((key, req))
        except Exception:
            pass

        # Scan raw source for feature guards
        feature_guards = []
        with open(path) as fh:
            raw = fh.read()
        for fm in re.finditer(r"host\.features\.(\w+(?:\.\w+)*)", raw):
            feat = fm.group(1)
            if feat not in feature_guards:
                feature_guards.append(feat)

        results.append((rel, state_ids, includes, requires, feature_guards))

    return results


def generate_states_md(state_results):
    """Generate salt-states.md content."""
    lines = [HEADER, "# Salt State Index\n"]

    for rel, state_ids, includes, requires, guards in state_results:
        basename = os.path.basename(rel).replace(".sls", "")
        lines.append(f"\n## {basename}")
        lines.append(f"**File:** `{rel}`\n")

        if includes:
            lines.append(f"**Includes:** {', '.join(f'`{i}`' for i in includes)}\n")

        if guards:
            lines.append(f"**Feature guards:** {', '.join(f'`{g}`' for g in guards)}\n")

        if state_ids:
            lines.append(f"**State IDs** ({len(state_ids)}):")
            for sid in state_ids:
                lines.append(f"- `{sid}`")
            lines.append("")

        if requires:
            lines.append("**Require chains:**")
            for from_id, to_ref in requires:
                lines.append(f"- `{from_id}` requires `{to_ref}`")
            lines.append("")

    return "\n".join(lines) + "\n"


# --- Data file summaries ---


def summarize_data_files():
    """Summarize YAML data files in states/data/."""
    data_dir = os.path.join(STATES_DIR, "data")
    if not os.path.isdir(data_dir):
        return []

    summaries = []
    for path in sorted(glob.glob(os.path.join(data_dir, "*.yaml"))):
        rel = os.path.relpath(path)
        try:
            with open(path) as f:
                data = yaml.safe_load(f.read())
        except Exception:
            summaries.append((rel, "Failed to parse"))
            continue

        if not isinstance(data, dict):
            summaries.append((rel, f"Root type: {type(data).__name__}"))
            continue

        sections = []
        for key, val in data.items():
            if isinstance(val, dict):
                sections.append(f"`{key}` ({len(val)} entries)")
            elif isinstance(val, list):
                sections.append(f"`{key}` ({len(val)} items)")
            else:
                sections.append(f"`{key}`: {val}")

        summaries.append((rel, sections))

    return summaries


def generate_data_md(summaries):
    """Generate salt-data.md content."""
    lines = [HEADER, "# Salt Data File Index\n"]

    for rel, info in summaries:
        basename = os.path.basename(rel)
        lines.append(f"\n## {basename}")
        lines.append(f"**File:** `{rel}`\n")

        if isinstance(info, str):
            lines.append(f"_{info}_\n")
        else:
            for section in info:
                lines.append(f"- {section}")
            lines.append("")

    return "\n".join(lines) + "\n"


def main():
    if not os.path.isdir(STATES_DIR):
        print(f"Error: {STATES_DIR} not found. Run from project root.", file=sys.stderr)
        sys.exit(1)

    os.makedirs(MEMORY_DIR, exist_ok=True)

    # 1. Macros
    jinja_files = sorted(glob.glob(os.path.join(STATES_DIR, "_macros_*.jinja")))
    macros = parse_macros(jinja_files)
    macros_md = generate_macros_md(macros)
    macros_path = os.path.join(MEMORY_DIR, "salt-macros.md")
    with open(macros_path, "w") as f:
        f.write(macros_md)
    print(f"Wrote {macros_path} ({len(macros)} macros, {macros_md.count(chr(10))} lines)")

    # 2. States
    sls_files = sorted(glob.glob(os.path.join(STATES_DIR, "*.sls")))
    state_results = render_states(sls_files)
    rendered_ok = sum(1 for _, ids, _, _, _ in state_results if ids)
    states_md = generate_states_md(state_results)
    states_path = os.path.join(MEMORY_DIR, "salt-states.md")
    with open(states_path, "w") as f:
        f.write(states_md)
    n_lines = states_md.count(chr(10))
    print(f"Wrote {states_path} ({len(sls_files)} files, {rendered_ok} rendered, {n_lines} lines)")

    # 3. Data files
    summaries = summarize_data_files()
    data_md = generate_data_md(summaries)
    data_path = os.path.join(MEMORY_DIR, "salt-data.md")
    with open(data_path, "w") as f:
        f.write(data_md)
    print(f"Wrote {data_path} ({len(summaries)} files, {data_md.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
