#!/usr/bin/env python3
"""Generate QML component and JS helper indexes for Claude Code memory.

Parses qmldir files for module structure, regex-scans QML files for public
properties/signals/functions, and JS files for function signatures.

Outputs markdown to memory/generated/qml-components.md and qml-helpers.md.
"""

import glob
import os
import re
import sys
from datetime import datetime

QML_DIR = os.path.join("dotfiles", "dot_config", "quickshell")
MEMORY_DIR = os.path.join(
    os.path.expanduser("~"), ".claude", "projects", "-home-neg-src-salt", "memory", "generated"
)

_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
HEADER = (
    "<!-- AUTO-GENERATED by scripts/index-qml.py"
    " — do not hand-edit -->\n"
    f"<!-- Last updated: {_ts} -->\n"
)

# --- Regexes ---
PROPERTY_RE = re.compile(
    r"^\s*(default\s+)?(required\s+)?(readonly\s+)?property\s+"
    r"(?:(var|bool|int|real|double|string|color|url|list|alias|font)\s+)?"
    r"(\w+)"
)
SIGNAL_RE = re.compile(r"^\s*signal\s+(\w+)\s*(\(.*?\))?")
FUNCTION_RE = re.compile(r"^\s*function\s+(\w+)\s*\((.*?)\)")
ROOT_TYPE_RE = re.compile(r"^([A-Z]\w[\w.]*)\s*\{")
JS_FUNCTION_RE = re.compile(r"^\s*function\s+(\w+)\s*\((.*?)\)")


def parse_qmldir(path):
    """Parse a qmldir file. Returns (module_name, [(name, version, file, singleton)])."""
    module = ""
    components = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("module "):
                module = line.split(None, 1)[1]
            elif line.startswith("singleton "):
                parts = line.split()
                if len(parts) >= 4:
                    components.append((parts[1], parts[2], parts[3], True))
            elif re.match(r"^[A-Z]", line):
                parts = line.split()
                if len(parts) >= 3:
                    components.append((parts[0], parts[1], parts[2], False))
    return module, components


def parse_qml_file(path):
    """Extract public API from a QML file."""
    with open(path) as f:
        lines = f.readlines()

    root_type = ""
    properties = []
    signals = []
    functions = []
    default_prop = None

    for line in lines:
        stripped = line.rstrip()

        # Root type: first line matching `TypeName {`
        if not root_type:
            m = ROOT_TYPE_RE.match(stripped)
            if m:
                root_type = m.group(1)
                continue

        # Default property alias
        if "default property alias" in stripped:
            m = re.search(r"default\s+property\s+alias\s+(\w+)\s*:\s*(.*)", stripped)
            if m:
                default_prop = f"{m.group(1)} -> {m.group(2).strip()}"
            continue

        # Property
        m = PROPERTY_RE.match(stripped)
        if m:
            name = m.group(5)
            if name.startswith("_"):
                continue
            ptype = m.group(4) or "var"
            readonly = bool(m.group(3))
            required = bool(m.group(2))
            flags = []
            if readonly:
                flags.append("readonly")
            if required:
                flags.append("required")
            flag_str = f" ({', '.join(flags)})" if flags else ""
            # Extract default value if simple single-line
            default = ""
            colon_idx = stripped.find(":", stripped.index(name) + len(name))
            if colon_idx >= 0 and "alias" not in stripped[:colon_idx]:
                val = stripped[colon_idx + 1 :].strip()
                if val and not val.startswith("{") and not val.startswith("("):
                    default = f" = {val}"
            properties.append(f"`{name}: {ptype}`{flag_str}{default}")
            continue

        # Signal
        m = SIGNAL_RE.match(stripped)
        if m:
            name = m.group(1)
            params = m.group(2) or "()"
            signals.append(f"`{name}{params}`")
            continue

        # Function (public only — skip _ prefixed)
        m = FUNCTION_RE.match(stripped)
        if m:
            name = m.group(1)
            if name.startswith("_"):
                continue
            params = m.group(2)
            functions.append(f"`{name}({params})`")

    return root_type, properties, signals, functions, default_prop


def parse_js_file(path):
    """Extract function signatures from a JS file."""
    functions = []
    with open(path) as f:
        for line in f:
            m = JS_FUNCTION_RE.match(line)
            if m:
                name = m.group(1)
                params = m.group(2)
                functions.append(f"`{name}({params})`")
    return functions


def discover_modules(qml_dir):
    """Find all qmldir files and parse them."""
    modules = {}
    for qmldir_path in sorted(glob.glob(os.path.join(qml_dir, "**/qmldir"), recursive=True)):
        module, components = parse_qmldir(qmldir_path)
        if module:
            base_dir = os.path.dirname(qmldir_path)
            modules[module] = {
                "dir": base_dir,
                "components": components,
            }
    return modules


def generate_components_md(modules, qml_dir):
    """Generate the QML components index markdown."""
    lines = [HEADER, "# QML Component Index\n"]

    for module_name in sorted(modules.keys()):
        mod = modules[module_name]
        lines.append(f"\n## {module_name}\n")

        for comp_name, version, filename, is_singleton in sorted(mod["components"]):
            filepath = os.path.join(mod["dir"], filename)
            if not os.path.isfile(filepath):
                continue

            rel_path = os.path.relpath(filepath)
            root_type, properties, signals, functions, default_prop = parse_qml_file(filepath)

            prefix = "**singleton** " if is_singleton else ""
            lines.append(f"### {prefix}{comp_name}")
            lines.append(f"**File:** `{rel_path}` **Root:** {root_type or '?'}\n")

            if properties:
                lines.append("**Properties:**")
                for p in properties:
                    lines.append(f"- {p}")
                lines.append("")

            if signals:
                lines.append("**Signals:**")
                for s in signals:
                    lines.append(f"- {s}")
                lines.append("")

            if functions:
                lines.append("**Functions:**")
                for fn in functions:
                    lines.append(f"- {fn}")
                lines.append("")

            if default_prop:
                lines.append(f"**Default property:** `{default_prop}`\n")

    return "\n".join(lines) + "\n"


def generate_helpers_md(qml_dir):
    """Generate the JS helpers index markdown."""
    lines = [HEADER, "# JS Helper Function Index\n"]

    js_files = sorted(glob.glob(os.path.join(qml_dir, "**/*.js"), recursive=True))
    for js_path in js_files:
        rel = os.path.relpath(js_path)
        fns = parse_js_file(js_path)
        if not fns:
            continue
        lines.append(f"\n## `{rel}`\n")
        for fn in fns:
            lines.append(f"- {fn}")

    return "\n".join(lines) + "\n"


def main():
    if not os.path.isdir(QML_DIR):
        print(f"Error: {QML_DIR} not found. Run from project root.", file=sys.stderr)
        sys.exit(1)

    os.makedirs(MEMORY_DIR, exist_ok=True)

    modules = discover_modules(QML_DIR)
    print(f"Found {len(modules)} modules:")
    for m in sorted(modules):
        print(f"  {m}: {len(modules[m]['components'])} components")

    # Components index
    comp_md = generate_components_md(modules, QML_DIR)
    comp_path = os.path.join(MEMORY_DIR, "qml-components.md")
    with open(comp_path, "w") as f:
        f.write(comp_md)
    comp_lines = comp_md.count("\n")
    print(f"Wrote {comp_path} ({comp_lines} lines)")

    # Helpers index
    helpers_md = generate_helpers_md(QML_DIR)
    helpers_path = os.path.join(MEMORY_DIR, "qml-helpers.md")
    with open(helpers_path, "w") as f:
        f.write(helpers_md)
    helpers_lines = helpers_md.count("\n")
    print(f"Wrote {helpers_path} ({helpers_lines} lines)")


if __name__ == "__main__":
    main()
