#!/bin/bash
set -euo pipefail

# Boot CachyOS rootfs in a QEMU VM to verify networking and services.
#
# Usage:
#   sudo ./scripts/test-cachyos-vm.sh [ROOTFS_DIR]
#
# Default rootfs: /var/mnt/one/cachyos-root
# Creates a temporary qcow2 image, copies rootfs into it, boots with UEFI.
# The VM gets a virtio NIC with user-mode networking (SLIRP) — DHCP auto.
# SSH forwarded to host port 2222.

ROOTFS="${1:-/var/mnt/one/cachyos-root}"
VM_DIR="/tmp/cachyos-vm"
DISK="${VM_DIR}/cachyos.qcow2"
OVMF_CODE="/usr/share/edk2/ovmf/OVMF_CODE.fd"
OVMF_VARS_TEMPLATE="/usr/share/edk2/ovmf/OVMF_VARS.fd"
OVMF_VARS="${VM_DIR}/OVMF_VARS.fd"
DISK_SIZE="20G"
MNT="${VM_DIR}/mnt"

# -------------------------------------------------------------------
# Validation
# -------------------------------------------------------------------

if [[ $EUID -ne 0 ]]; then
    echo "error: must run as root (need mount/losetup)" >&2
    exit 1
fi

if [[ ! -d "$ROOTFS/usr/bin" ]]; then
    echo "error: $ROOTFS doesn't look like a rootfs (no usr/bin)" >&2
    echo "  run bootstrap-cachyos.sh first" >&2
    exit 1
fi

if [[ ! -f "$OVMF_CODE" ]]; then
    echo "error: OVMF not found at $OVMF_CODE" >&2
    echo "  install edk2-ovmf" >&2
    exit 1
fi

# -------------------------------------------------------------------
# Build disk image
# -------------------------------------------------------------------

echo "==> Creating VM disk image..."
mkdir -p "$VM_DIR" "$MNT"
rm -f "$DISK"
qemu-img create -f qcow2 "$DISK" "$DISK_SIZE"

# Connect qcow2 via NBD
modprobe nbd max_part=8
qemu-nbd --connect=/dev/nbd0 "$DISK"
trap 'echo "==> Cleaning up..."; umount -R "$MNT" 2>/dev/null || true; qemu-nbd --disconnect /dev/nbd0 2>/dev/null || true' EXIT

# Partition: 512M EFI + rest btrfs
echo "==> Partitioning..."
parted -s /dev/nbd0 -- mklabel gpt
parted -s /dev/nbd0 -- mkpart ESP fat32 1MiB 513MiB
parted -s /dev/nbd0 -- set 1 esp on
parted -s /dev/nbd0 -- mkpart root btrfs 513MiB 100%

# Wait for partition devices
sleep 1
partprobe /dev/nbd0
sleep 1

echo "==> Formatting..."
mkfs.fat -F32 -n EFI /dev/nbd0p1
mkfs.btrfs -f -L cachyos /dev/nbd0p2

# Create btrfs subvolumes
echo "==> Creating btrfs subvolumes..."
mount /dev/nbd0p2 "$MNT"
btrfs subvolume create "$MNT/@"
btrfs subvolume create "$MNT/@home"
btrfs subvolume create "$MNT/@cache"
btrfs subvolume create "$MNT/@log"
btrfs subvolume create "$MNT/@snapshots"
umount "$MNT"

# Mount subvolumes
echo "==> Mounting subvolumes..."
mount -o subvol=@,compress=zstd:1,noatime /dev/nbd0p2 "$MNT"
mkdir -p "$MNT"/{home,boot/efi,.snapshots,var/cache,var/log}
mount -o subvol=@home,compress=zstd:1,noatime /dev/nbd0p2 "$MNT/home"
mount -o subvol=@snapshots,compress=zstd:1,noatime /dev/nbd0p2 "$MNT/.snapshots"
mount -o subvol=@cache,compress=zstd:1,noatime /dev/nbd0p2 "$MNT/var/cache"
mount -o subvol=@log,compress=zstd:1,noatime /dev/nbd0p2 "$MNT/var/log"
mount /dev/nbd0p1 "$MNT/boot/efi"

# Copy rootfs
echo "==> Copying rootfs (this takes a while)..."
rsync -aAXH --info=progress2 "$ROOTFS/" "$MNT/"

# Generate fstab
echo "==> Generating fstab..."
EFI_UUID=$(blkid -s UUID -o value /dev/nbd0p1)
ROOT_UUID=$(blkid -s UUID -o value /dev/nbd0p2)

cat > "$MNT/etc/fstab" <<FSTAB
# CachyOS VM fstab (generated by test-cachyos-vm.sh)
UUID=${ROOT_UUID}  /              btrfs  subvol=@,compress=zstd:1,noatime          0  0
UUID=${ROOT_UUID}  /home          btrfs  subvol=@home,compress=zstd:1,noatime      0  0
UUID=${ROOT_UUID}  /.snapshots    btrfs  subvol=@snapshots,compress=zstd:1,noatime 0  0
UUID=${ROOT_UUID}  /var/cache     btrfs  subvol=@cache,compress=zstd:1,noatime     0  0
UUID=${ROOT_UUID}  /var/log       btrfs  subvol=@log,compress=zstd:1,noatime       0  0
UUID=${EFI_UUID}   /boot/efi      vfat   umask=0077                                0  1
FSTAB

# Update Limine config to use UUID instead of LABEL
echo "==> Updating bootloader config..."
cat > "$MNT/boot/limine.conf" <<LIMINE
timeout: 5
default_entry: 1
interface_branding: CachyOS VM

/CachyOS
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos
    kernel_cmdline: root=UUID=${ROOT_UUID} rootflags=subvol=@ rw console=ttyS0,115200 console=tty0
    module_path: boot():/initramfs-linux-cachyos.img

/CachyOS (fallback)
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos
    kernel_cmdline: root=UUID=${ROOT_UUID} rootflags=subvol=@ rw console=ttyS0,115200 console=tty0
    module_path: boot():/initramfs-linux-cachyos-fallback.img
LIMINE

# Copy Limine EFI to ESP
mkdir -p "$MNT/boot/efi/EFI/BOOT"
if [[ -f "$MNT/usr/share/limine/BOOTX64.EFI" ]]; then
    cp "$MNT/usr/share/limine/BOOTX64.EFI" "$MNT/boot/efi/EFI/BOOT/BOOTX64.EFI"
    # Also copy limine.conf to ESP root for Limine to find it
    cp "$MNT/boot/limine.conf" "$MNT/boot/efi/limine.conf"
    echo "  Limine EFI installed"
else
    echo "  WARNING: Limine EFI binary not found, using systemd-boot fallback"
    # Fallback: use systemd-boot if available
    if [[ -f "$MNT/usr/lib/systemd/boot/efi/systemd-bootx64.efi" ]]; then
        cp "$MNT/usr/lib/systemd/boot/efi/systemd-bootx64.efi" "$MNT/boot/efi/EFI/BOOT/BOOTX64.EFI"
        mkdir -p "$MNT/boot/efi/loader/entries"
        cat > "$MNT/boot/efi/loader/loader.conf" <<LOADER
default cachyos.conf
timeout 5
LOADER
        cat > "$MNT/boot/efi/loader/entries/cachyos.conf" <<ENTRY
title   CachyOS VM
linux   /vmlinuz-linux-cachyos
initrd  /initramfs-linux-cachyos.img
options root=UUID=${ROOT_UUID} rootflags=subvol=@ rw console=ttyS0,115200 console=tty0
ENTRY
        # Copy kernel + initramfs to ESP
        cp "$MNT/boot/vmlinuz-linux-cachyos" "$MNT/boot/efi/" 2>/dev/null || true
        cp "$MNT/boot/initramfs-linux-cachyos.img" "$MNT/boot/efi/" 2>/dev/null || true
    fi
fi

echo "==> Unmounting..."
umount -R "$MNT"
qemu-nbd --disconnect /dev/nbd0
trap - EXIT

# Copy OVMF vars (writable copy needed per VM)
cp "$OVMF_VARS_TEMPLATE" "$OVMF_VARS"

# -------------------------------------------------------------------
# Boot VM
# -------------------------------------------------------------------

echo ""
echo "==> Booting CachyOS VM..."
echo "    SSH: ssh -p 2222 neg@localhost (password: changeme)"
echo "    Console: serial output below"
echo "    Quit: Ctrl-A X"
echo ""

qemu-system-x86_64 \
    -machine q35,accel=kvm \
    -cpu host \
    -smp 4 \
    -m 4G \
    -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE" \
    -drive if=pflash,format=raw,file="$OVMF_VARS" \
    -drive file="$DISK",format=qcow2,if=virtio \
    -nic user,model=virtio-net-pci,hostfwd=tcp::2222-:22 \
    -nographic \
    -serial mon:stdio
