daemon_options = spotless

im {
    command = Telegram
    class = org.telegram.desktop
    options = shiny
    rules = float on; size 15% 48%
}

music {
    command = kitty --single-instance --class music -e rmpc
    class = music
    rules = float on; size 35% 20%
}

torrment {
    command = kitty --single-instance --class torrment -e rustmission
    class = torrment
    rules = float on; size 49% 20%; move 1% 0%
}

teardown {
    command = kitty --single-instance --class teardown -e btop
    class = teardown
    options = shiny
    rules = float on; size 49% 25%; move 1% 0%
}

mixer {
    command = kitty --single-instance --class mixer -e pipemixer
    class = mixer
    rules = float on; size 20% 45%; move 79% 5%
}
