daemon_options = spotless

im {
    command = Telegram
    class = org.telegram.desktop
    options = shiny
    rules = float on; size 480 740
}

music {
    command = kitty --single-instance --class music -e rmpc
    class = music
    rules = float on; size 1200 480
}

torrment {
    command = kitty --single-instance --class torrment -e rustmission
    class = torrment
    rules = float on; size 1440 420
}

teardown {
    command = kitty --single-instance --class teardown -e btop
    class = teardown
    options = shiny
    rules = float on; size 1440 460
}

mixer {
    command = kitty --single-instance --class mixer -e pipemixer
    class = mixer
    rules = float on; size 620 840
}

amnezia {
    command = /usr/local/bin/AmneziaVPN
    class = AmneziaVPN
    rules = float on; size 960 860
}
