daemon_options = spotless

im {
    command = Telegram
    class = org.telegram.desktop
    options = shiny
    rules = float on; size 30% 95%; move 69% 2%
}

music {
    command = kitty --single-instance --class music -e rmpc
    class = music
    rules = float on; size 70% 40%; move 15% 50%
}

torrment {
    command = kitty --single-instance --class torrment -e rustmission
    class = torrment
    rules = float on; size 98% 40%; move 1% 0%
}

teardown {
    command = kitty --single-instance --class teardown -e btop
    class = teardown
    options = shiny
    rules = float on; size 98% 50%; move 1% 0%
}

mixer {
    command = kitty --single-instance --class mixer -e pipemixer
    class = mixer
    rules = float on; size 40% 90%; move 59% 5%
}
