workspace = 1, defaultName:𐌰:term
workspace = 2, defaultName:𐌱:web
workspace = 3, defaultName:𐌲:dev
workspace = 4, defaultName:𐌸:games, gapsout:0, gapsin:0, layout:monocle
workspace = 5, defaultName:𐌳:doc
workspace = 6, defaultName:𐌴:draw
workspace = 7, defaultName:𐌵:vid
workspace = 8, defaultName:𐌶:obs
workspace = 9, defaultName:𐌷:pic
workspace = 10, defaultName:𐌹:sys
workspace = 11, defaultName:𐌺:vm
workspace = 12, defaultName:𐌻:wine
workspace = 13, defaultName:𐌼:patchbay
workspace = 14, defaultName:𐌽:daw
workspace = 15, defaultName:𐌾:dw
workspace = 16, defaultName:𐌿:keyboard
workspace = 17, defaultName:𐍀:im
workspace = 18, defaultName:𐍁:remote
workspace = 19, defaultName:Ⲣ:notes
workspace = 20, defaultName:𐍅:winboat
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float false, match:workspace w[tv1]
windowrule = rounding 0, match:float false, match:workspace w[tv1]
windowrule = border_size 0, match:float false, match:workspace f[1]
windowrule = rounding 0, match:float false, match:workspace f[1]

# swayimg
windowrule = float on, match:class ^(swayimg)$
windowrule = size 1200 800, match:class ^(swayimg)$
windowrule = move 100 100, match:class ^(swayimg)$

# routing
windowrule = no_blur on, $term
windowrule = workspace name:𐌰:term, $term
windowrule = workspace name:𐌱:web, $web
windowrule = workspace name:𐌲:dev, $dev
windowrule = workspace name:𐌸:games, $games
windowrule = border_size 0, match:float false, match:workspace name:𐌸:games
windowrule = rounding 0, match:float false, match:workspace name:𐌸:games
windowrule = workspace name:𐌳:doc, $doc
windowrule = workspace name:𐌵:vid, $vid
windowrule = workspace name:𐌶:obs, $obs
windowrule = workspace name:𐌷:pic, $pic
windowrule = workspace name:𐌼:patchbay, $patchbay
windowrule = workspace name:𐌽:daw, $daw
windowrule = workspace name:𐌾:dw, $dw
windowrule = workspace name:𐌿:keyboard, $keyboard
windowrule = workspace name:𐍁:remote, $remote
windowrule = workspace name:𐍀:im, $im
windowrule = workspace name:Ⲣ:notes, $notes
windowrule = workspace name:𐌺:vm, $vm
windowrule = workspace name:𐌻:wine, $wine
windowrule = workspace name:winboat, $winboat
windowrule = float on, match:workspace 20

# special
windowrule = fullscreen on, $pic
