workspace = 1, defaultName:𐌰:term
workspace = 2, defaultName:𐌱:web
workspace = 3, defaultName:𐌲:dev
workspace = 4, defaultName:𐌸:games, gapsout:0, gapsin:0, layout:monocle
workspace = 5, defaultName:𐌳:doc
workspace = 6, defaultName:𐌴:draw
workspace = 7, defaultName:𐌵:vid
workspace = 8, defaultName:𐌶:obs
workspace = 9, defaultName:𐌷:pic
workspace = 10, defaultName:𐌹:sys
workspace = 11, defaultName:𐌺:vm
workspace = 12, defaultName:𐌻:wine
workspace = 13, defaultName:𐌼:patchbay
workspace = 14, defaultName:𐌽:daw
workspace = 15, defaultName:𐌾:dw
workspace = 16, defaultName:𐌿:keyboard
workspace = 17, defaultName:𐍀:im
workspace = 18, defaultName:𐍁:remote
workspace = 19, defaultName:Ⲣ:notes
workspace = 20, defaultName:𐍅:winboat
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
# hide borders on all tiled windows (scrolling layout)
windowrule = border_size 0, match:float false
# hide borders when only one tiled window on workspace
windowrule = border_size 0, match:float false, match:workspace w[t1]
windowrule = border_size 0, match:float false, match:workspace w[tv1]
windowrule = rounding 0, match:float false, match:workspace w[tv1]
windowrule = border_size 0, match:float false, match:workspace f[1]
windowrule = rounding 0, match:float false, match:workspace f[1]

# swayimg
windowrule = float on, match:class ^(swayimg)$
windowrule = size 1200 800, match:class ^(swayimg)$
windowrule = move 100 100, match:class ^(swayimg)$

# routing
windowrule = $term, no_blur on
windowrule = $term, workspace 1
windowrule = match:class ^(zen)$, workspace 2 silent
windowrule = match:initial_class ^(zen)$, workspace 2 silent
windowrule = $web, workspace 2 silent
windowrule = $dev, workspace 3
windowrule = $games, workspace 4
windowrule = border_size 0, match:float false, match:workspace 4
windowrule = rounding 0, match:float false, match:workspace 4
windowrule = $doc, workspace 5
windowrule = $vid, workspace 7
windowrule = $obs, workspace 8
windowrule = $pic, workspace 9
windowrule = $patchbay, workspace 13
windowrule = $daw, workspace 14
windowrule = $dw, workspace 15
windowrule = $keyboard, workspace 16
windowrule = $remote, workspace 18
windowrule = $im, workspace 17
windowrule = $notes, workspace 19
windowrule = $vm, workspace 11
windowrule = $wine, workspace 12
windowrule = $winboat, workspace 20
windowrule = float on, match:workspace 20

# special
windowrule = fullscreen on, $pic
