workspace = 1, defaultName:𐌰:term
workspace = 2, defaultName:𐌱:web
workspace = 3, defaultName:𐌲:dev
workspace = 4, defaultName:𐌸:games, gapsout:0, gapsin:0
workspace = 5, defaultName:𐌳:doc
workspace = 6, defaultName:𐌴:draw
workspace = 7, defaultName:𐌵:vid
workspace = 8, defaultName:𐌶:obs
workspace = 9, defaultName:𐌷:pic
workspace = 10, defaultName:𐌹:sys
workspace = 11, defaultName:𐌺:vm
workspace = 12, defaultName:𐌻:wine
workspace = 13, defaultName:𐌼:patchbay
workspace = 14, defaultName:𐌽:daw
workspace = 15, defaultName:𐌾:dw
workspace = 16, defaultName:𐌿:keyboard
workspace = 17, defaultName:𐍀:im
workspace = 18, defaultName:𐍁:remote
workspace = 19, defaultName:Ⲣ:notes
workspace = 20, defaultName:𐍅:winboat
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float false, match:workspace w[tv1]
windowrule = rounding 0, match:float false, match:workspace w[tv1]
windowrule = border_size 0, match:float false, match:workspace f[1]
windowrule = rounding 0, match:float false, match:workspace f[1]

# swayimg
windowrule = float on, match:class ^(swayimg)$
windowrule = size 1200 800, match:class ^(swayimg)$
windowrule = move 100 100, match:class ^(swayimg)$

# routing
windowrule = no_blur on, $term
windowrule = workspace 1, $term
windowrule = workspace 2, $web
windowrule = workspace 3, $dev
windowrule = workspace 4, $games
windowrule = fullscreen maximize, match:float false, match:workspace 4
windowrule = border_size 0, match:float false, match:workspace 4
windowrule = rounding 0, match:float false, match:workspace 4
windowrule = workspace 5, $doc
windowrule = workspace 7, $vid
windowrule = workspace 8, $obs
windowrule = workspace 9, $pic
windowrule = workspace 13, $patchbay
windowrule = workspace 14, $daw
windowrule = workspace 15, $dw
windowrule = workspace 16, $keyboard
windowrule = workspace 18, $remote
windowrule = workspace 17, $im
windowrule = workspace 19, $notes
windowrule = workspace 11, $vm
windowrule = workspace 12, $wine
windowrule = workspace 20, $winboat
windowrule = float on, match:workspace 20

# special
windowrule = fullscreen on, $pic
